'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');
const test = require('node:test');
const assert = require('node:assert/strict');
const { hashBytes } = require('../src/stable');

const projectRoot = path.resolve(__dirname, '..');
const cli = path.join(projectRoot, 'bin', 'homer.js');
const fixtureRoot = path.join(__dirname, 'fixtures', 'run');

function run(args, cwd = projectRoot) {
  return spawnSync(process.execPath, [cli, ...args], { cwd, encoding: 'utf8', windowsHide: true });
}

function copyRunFixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'homer-cli-'));
  fs.cpSync(fixtureRoot, root, { recursive: true });
  return root;
}

function directoryFingerprint(root) {
  const files = [];
  function visit(directory) {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      const child = path.join(directory, entry.name);
      if (entry.isDirectory()) visit(child);
      else files.push(`${path.relative(root, child)}\0${hashBytes(fs.readFileSync(child))}`);
    }
  }
  visit(root);
  return hashBytes(files.join('\n'));
}

function copyPortablePackages() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'homer-portable-cli-'));
  const source = path.join(root, 'source');
  const target = path.join(root, 'target');
  fs.mkdirSync(source, { recursive: true });
  fs.mkdirSync(target, { recursive: true });
  fs.cpSync(path.join(projectRoot, 'packages'), path.join(source, 'packages'), { recursive: true });
  fs.cpSync(path.join(projectRoot, 'profiles'), path.join(source, 'profiles'), { recursive: true });
  fs.cpSync(path.join(projectRoot, 'adapters'), path.join(source, 'adapters'), { recursive: true });
  fs.writeFileSync(path.join(target, 'AGENTS.md'), '# Target-owned routing\n');
  return { root, source, target, profile: path.join(source, 'profiles', 'studio.json') };
}

test('inspect is deterministic and does not mutate the target', () => {
  const root = copyRunFixture();
  const before = directoryFingerprint(path.join(root, 'target'));
  const first = run(['inspect', '--config', path.join(root, 'homer.yaml')]);
  const second = run(['inspect', '--config', path.join(root, 'homer.yaml')]);
  assert.equal(first.status, 0, first.stderr);
  assert.equal(second.status, 0, second.stderr);
  assert.equal(first.stdout, second.stdout);
  assert.equal(directoryFingerprint(path.join(root, 'target')), before);
  const inventory = JSON.parse(first.stdout);
  assert.equal(inventory.kind, 'OdysseyInventory');
});

test('plan and diff expose generated, preserved, and authority changes', () => {
  const root = copyRunFixture();
  const planResult = run(['plan', '--config', path.join(root, 'homer.yaml')]);
  const diffResult = run(['diff', '--config', path.join(root, 'homer.yaml')]);
  assert.equal(planResult.status, 0, planResult.stderr);
  assert.equal(diffResult.status, 0, diffResult.stderr);
  const plan = JSON.parse(planResult.stdout);
  const diff = JSON.parse(diffResult.stdout);
  assert.equal(plan.accepted, false);
  assert.equal(plan.planId, diff.planId);
  assert.ok(diff.additions.length >= 2);
  assert.ok(diff.preservedTargetOwned.includes('AGENTS.md'));
  assert.deepEqual(diff.authorityChanges.allowed, ['filesystem.read']);
});

test('diff distinguishes generated replacements and removals', () => {
  const root = copyRunFixture();
  const generatedRoot = path.join(root, 'target', '.homer', 'generated', 'skills');
  const projected = path.join(generatedRoot, 'ralph', 'SKILL.md');
  const stale = path.join(generatedRoot, 'stale', 'SKILL.md');
  fs.mkdirSync(path.dirname(projected), { recursive: true });
  fs.mkdirSync(path.dirname(stale), { recursive: true });
  const marker = '<!-- Generated by Homer Odyssey; do not edit directly. -->\n';
  fs.writeFileSync(projected, `${marker}old projected content\n`);
  fs.writeFileSync(stale, `${marker}stale projected content\n`);
  const result = run(['diff', '--config', path.join(root, 'homer.yaml')]);
  assert.equal(result.status, 0, result.stderr);
  const diff = JSON.parse(result.stdout);
  assert.ok(diff.replacements.some((item) => item.path.endsWith('ralph/SKILL.md')));
  assert.ok(diff.removals.some((item) => item.path.endsWith('stale/SKILL.md')));
});

test('missing reference returns exit 11', () => {
  const root = copyRunFixture();
  fs.appendFileSync(path.join(root, 'source', '.agents', 'skills', 'ralph', 'SKILL.md'), '\n[missing](./missing.md)\n');
  const result = run(['inspect', '--config', path.join(root, 'homer.yaml')]);
  assert.equal(result.status, 11, result.stderr);
  assert.equal(JSON.parse(result.stdout).summary.missingDependencies, 1);
});

test('protected projection returns exit 12 with evidence', () => {
  const root = copyRunFixture();
  const profilePath = path.join(root, 'profile.json');
  const profile = JSON.parse(fs.readFileSync(profilePath, 'utf8'));
  profile.projection.mappings[0].target = 'AGENTS.md';
  fs.writeFileSync(profilePath, `${JSON.stringify(profile, null, 2)}\n`);
  const result = run(['plan', '--config', path.join(root, 'homer.yaml')]);
  assert.equal(result.status, 12, result.stderr);
  assert.ok(JSON.parse(result.stdout).conflicts.some((item) => item.type === 'protected-path'));
});

test('unsafe privilege increase returns exit 13 with evidence', () => {
  const root = copyRunFixture();
  fs.appendFileSync(path.join(root, 'source', '.agents', 'skills', 'ralph', 'SKILL.md'), '\nhomer-capability: production.mutate\n');
  const result = run(['plan', '--config', path.join(root, 'homer.yaml')]);
  assert.equal(result.status, 13, result.stderr);
  assert.deepEqual(JSON.parse(result.stdout).privilegeDelta.denied, ['production.mutate']);
});

test('managed target customization returns exit 14 and is preserved', () => {
  const root = copyRunFixture();
  const customized = path.join(root, 'target', '.homer', 'generated', 'skills', 'ralph', 'SKILL.md');
  fs.mkdirSync(path.dirname(customized), { recursive: true });
  fs.writeFileSync(customized, 'Studio-owned customization\n');
  const result = run(['plan', '--config', path.join(root, 'homer.yaml')]);
  assert.equal(result.status, 14, result.stderr);
  const plan = JSON.parse(result.stdout);
  assert.ok(plan.conflicts.some((item) => item.type === 'customization'));
  assert.ok(plan.preservedPaths.includes('.homer/generated/skills/ralph/SKILL.md'));
});

test('invalid profile returns exit 10 and no artifact', () => {
  const root = copyRunFixture();
  const profilePath = path.join(root, 'profile.json');
  const profile = JSON.parse(fs.readFileSync(profilePath, 'utf8'));
  profile.capabilities.denied.push('filesystem.read');
  fs.writeFileSync(profilePath, `${JSON.stringify(profile, null, 2)}\n`);
  const result = run(['inspect', '--config', path.join(root, 'homer.yaml')]);
  assert.equal(result.status, 10);
  assert.equal(result.stdout, '');
  assert.match(result.stderr, /ambiguous policy/i);
});

test('accepted portable plan supports dry-run, apply, verify, and rollback through the CLI', () => {
  const state = copyPortablePackages();
  const common = ['--source', state.source, '--target', state.target, '--profile', state.profile];
  const planned = run(['plan', ...common, '--accept']);
  assert.equal(planned.status, 0, planned.stderr);
  const plan = JSON.parse(planned.stdout);
  assert.equal(plan.accepted, true);
  const planPath = path.join(state.root, 'accepted-plan.json');
  fs.writeFileSync(planPath, planned.stdout);

  const before = directoryFingerprint(state.target);
  const preview = run(['apply', ...common, '--plan', planPath, '--dry-run']);
  assert.equal(preview.status, 0, preview.stderr);
  assert.equal(JSON.parse(preview.stdout).dryRun, true);
  assert.equal(directoryFingerprint(state.target), before);

  const applied = run(['apply', ...common, '--plan', planPath]);
  assert.equal(applied.status, 0, applied.stderr);
  assert.ok(JSON.parse(applied.stdout).writes.length > 20);
  assert.equal(fs.readFileSync(path.join(state.target, 'AGENTS.md'), 'utf8'), '# Target-owned routing\n');

  const verified = run(['verify', ...common]);
  assert.equal(verified.status, 0, verified.stderr);
  assert.equal(JSON.parse(verified.stdout).verdict, 'PASS');

  const rollbackPreview = run(['rollback', ...common, '--dry-run']);
  assert.equal(rollbackPreview.status, 0, rollbackPreview.stderr);
  assert.equal(JSON.parse(rollbackPreview.stdout).dryRun, true);
  const rolledBack = run(['rollback', ...common]);
  assert.equal(rolledBack.status, 0, rolledBack.stderr);
  assert.equal(fs.existsSync(path.join(state.target, 'homer.lock')), false);
  assert.equal(fs.readFileSync(path.join(state.target, 'AGENTS.md'), 'utf8'), '# Target-owned routing\n');
});
