'use strict';

const { normalizePath } = require('../src/glob');

const TARGET_MARKER = '<!-- Generated by Homer Odyssey installer; do not edit directly. -->';

function yamlString(value) {
  return JSON.stringify(String(value));
}

function renderCodexTargetSkill({
  characterId,
  characterPackage,
  humanGatedCapabilities,
  nativeName,
  packageCore,
  profile,
  skillPackage,
  targetOverlay,
}) {
  const policy = profile.sanitization;
  const characterRoot = `.homer/generated/install/characters/${characterId}`;
  const skillRoot = `.homer/generated/install/skills/${skillPackage.id}`;
  const requiredHelpers = skillPackage.descriptor.dependencies.helpers
    .map((helper) => `   - \`${normalizePath(`${skillRoot}/${helper}`)}\``)
    .join('\n');
  const precedence = policy.localPrecedence.map((item) => `   - \`${item}\``).join('\n');
  const validators = policy.validationCommands.map((item) => `- \`${item}\``).join('\n') || '- None declared; stop and request target policy review.';
  const gates = humanGatedCapabilities.map((item) => `- \`${item}\``).join('\n') || '- No additional capability is granted by this package.';
  const overlaySection = targetOverlay.trim()
    ? `\n## Target overlay\n\n${targetOverlay.trim()}\n`
    : '';

  return `---
name: ${nativeName}
description: ${yamlString(`Use ${nativeName} for ${skillPackage.descriptor.title.toLowerCase()} under target-owned policy and approval gates.`)}
---

${TARGET_MARKER}
<!-- Homer package: skill:${skillPackage.id}@${skillPackage.version}; package-sha256: ${skillPackage.hash}; character:${characterId}@${characterPackage.version} -->

# ${skillPackage.descriptor.title}

This is a native Codex skill projected for \`${policy.targetRepository}\`. Character identity shapes judgment; the workflow below defines the work. Neither one grants authority beyond target-owned policy.

## Required reading

1. Read target \`AGENTS.md\` first.
2. Read \`${characterRoot}/passport.json\` and \`${characterRoot}/core.md\`.
3. Read \`${skillRoot}/manifest.json\` and \`${skillRoot}/core.md\`.
4. Read the packaged helpers:
${requiredHelpers || '   - No helper files declared.'}
5. Apply these target-owned sources with higher precedence:
${precedence}

If portable text conflicts with a target rule, stop and follow the target rule. Never edit files below \`.homer/generated/\` directly; rerun Homer after changing canonical packages or target policy.

## Target contract

- Repository: \`${policy.targetRepository}\`
- Base branch: \`${policy.targetBaseBranch}\`
- Native invocation: \`$${nativeName}\`
- Portable package authority is descriptive only; writes, publishing, deployment, and merges remain subject to the target human approval model.

Target validation commands:

${validators}

Human-gated capabilities retained as gates, not automatic authority:

${gates}

## Operational workflow

${packageCore.trim()}
${overlaySection}
## Completion rule

Return evidence, decisions, validation, risks, and the next human gate. Do not claim completion for an action the target policy did not authorize.
`;
}

module.exports = { TARGET_MARKER, renderCodexTargetSkill };
