'use strict';

const API_VERSION = 'homer.odyssey/v1';
const VERSION = '0.4.0';

const EXIT = Object.freeze({
  OK: 0,
  USAGE: 2,
  INVALID_CONTRACT: 10,
  MISSING_DEPENDENCY: 11,
  PROTECTED_CONFLICT: 12,
  UNSAFE_PRIVILEGE: 13,
  CUSTOMIZATION_CONFLICT: 14,
  PLAN_NOT_ACCEPTED: 15,
  SECURITY_POLICY: 16,
  EVAL_FAILED: 17,
  DRIFT: 18,
  ROLLBACK_FAILED: 19,
  POLICY_REVIEW_REQUIRED: 20,
  INTERNAL: 70,
});

module.exports = { API_VERSION, EXIT, VERSION };
