'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { renderCodexTargetSkill, TARGET_MARKER } = require('../adapters/codex-target');
const { resolveDependencies } = require('../transforms/dependency-resolver');
const { loadCatalog } = require('./catalog');
const { loadProfile } = require('./config');
const { API_VERSION, EXIT, VERSION } = require('./constants');
const { HomerError } = require('./errors');
const { matchesAny, normalizePath } = require('./glob');
const { assertContract } = require('./schema');
const {
  enforceMinimumVersions,
  evaluatePackageCapabilities,
  sanitizeText,
  scanSanitizedContent,
  validateInstallPolicy,
} = require('./sanitization');
const { hashBytes, hashObject, stableJson } = require('./stable');

const projectRoot = path.resolve(__dirname, '..');
const INSTALL_LOCK_PATH = '.homer/generated/install/install-lock.json';
const GENERATED_MARKER = '<!-- Generated by Homer Odyssey installer; do not edit directly. -->';
const CHARACTER_BY_SKILL = Object.freeze({
  lisa: 'lisa',
  'lisa-prime': 'lisa-prime',
  lorie: 'lorie',
  'marge-product-architect': 'marge',
  ralph: 'ralph',
  'ralph-prime': 'ralph-prime',
});

function readJson(filePath, label) {
  try { return JSON.parse(fs.readFileSync(filePath, 'utf8')); }
  catch (error) { throw new HomerError(`Cannot read ${label} at ${filePath}: ${error.message}`, EXIT.INVALID_CONTRACT); }
}

function isInside(root, candidate) {
  const resolvedRoot = path.resolve(root);
  const resolved = path.resolve(candidate);
  return resolved !== resolvedRoot && resolved.toLowerCase().startsWith(`${resolvedRoot}${path.sep}`.toLowerCase());
}

function targetPath(targetRoot, relativePath) {
  const normalized = normalizePath(relativePath);
  if (!normalized || path.isAbsolute(normalized) || normalized.split('/').includes('..')) {
    throw new HomerError(`Installer path escapes target root: ${relativePath}`, EXIT.PROTECTED_CONFLICT);
  }
  const absolute = path.resolve(targetRoot, ...normalized.split('/'));
  if (!isInside(targetRoot, absolute)) throw new HomerError(`Installer path escapes target root: ${relativePath}`, EXIT.PROTECTED_CONFLICT);
  let cursor = targetRoot;
  for (const segment of normalized.split('/').slice(0, -1)) {
    cursor = path.join(cursor, segment);
    if (fs.existsSync(cursor) && fs.lstatSync(cursor).isSymbolicLink()) {
      throw new HomerError(`Installer path traverses a symbolic link or junction: ${relativePath}`, EXIT.PROTECTED_CONFLICT);
    }
  }
  return absolute;
}

function atomicWrite(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const temporary = `${filePath}.homer-install-tmp`;
  fs.writeFileSync(temporary, content);
  fs.renameSync(temporary, filePath);
}

function walkFiles(root, relative = '') {
  if (!fs.existsSync(path.join(root, relative))) return [];
  return fs.readdirSync(path.join(root, relative), { withFileTypes: true })
    .filter((entry) => !['.git', 'node_modules'].includes(entry.name))
    .sort((left, right) => left.name.localeCompare(right.name))
    .flatMap((entry) => {
      const child = path.join(relative, entry.name);
      return entry.isDirectory() ? walkFiles(root, child) : [normalizePath(child)];
    });
}

function removeEmptyParents(targetRoot, relativePath, stopRoot) {
  let directory = path.dirname(targetPath(targetRoot, relativePath));
  const stop = path.resolve(targetRoot, ...normalizePath(stopRoot).split('/'));
  while (directory.toLowerCase().startsWith(stop.toLowerCase()) && directory.toLowerCase() !== path.resolve(targetRoot).toLowerCase()) {
    if (!fs.existsSync(directory) || fs.readdirSync(directory).length) break;
    fs.rmdirSync(directory);
    if (directory.toLowerCase() === stop.toLowerCase()) break;
    directory = path.dirname(directory);
  }
}

function resolveTargetProfile(targetRoot, profileValue) {
  if (!profileValue) throw new HomerError('homer install requires --profile <target-profile-path>', EXIT.USAGE);
  const profilePath = path.isAbsolute(profileValue) ? path.resolve(profileValue) : path.resolve(targetRoot, profileValue);
  if (!isInside(targetRoot, profilePath)) throw new HomerError('Install profile must be owned by the target repository', EXIT.INVALID_CONTRACT);
  const loaded = loadProfile(profilePath);
  const policy = validateInstallPolicy(loaded.profile);
  return { ...loaded, policy, profilePath };
}

function installerManaged(relativePath, policy) {
  const normalized = normalizePath(relativePath).replace(/\/$/, '');
  if (normalized.startsWith('.homer/generated/install/')) return true;
  return policy.managedNativeSkillPaths.some((root) => normalized === normalizePath(root) || normalized.startsWith(`${normalizePath(root)}/`));
}

function assertInstallerPath(relativePath, policy) {
  const normalized = normalizePath(relativePath);
  if (!installerManaged(normalized, policy)) throw new HomerError(`Path is not installer-managed: ${relativePath}`, EXIT.PROTECTED_CONFLICT);
  const nativeException = policy.managedNativeSkillPaths.some((root) => normalized === normalizePath(root) || normalized.startsWith(`${normalizePath(root)}/`));
  if (matchesAny(normalized, policy.protectedPaths) && !nativeException) {
    throw new HomerError(`Path is protected by target sanitization policy: ${relativePath}`, EXIT.PROTECTED_CONFLICT);
  }
}

function targetOwnedFingerprint(targetRoot, policy) {
  const records = walkFiles(targetRoot)
    .filter((relativePath) => relativePath !== INSTALL_LOCK_PATH && !installerManaged(relativePath, policy))
    .map((relativePath) => ({ path: relativePath, hash: hashBytes(fs.readFileSync(targetPath(targetRoot, relativePath))) }));
  return hashObject(records);
}

function readTargetOverlays(targetRoot, policy) {
  return policy.requiredOverlays.map((relativePath) => {
    const absolute = targetPath(targetRoot, relativePath);
    if (!fs.existsSync(absolute) || !fs.statSync(absolute).isFile()) {
      throw new HomerError(`Required target overlay is missing: ${relativePath}`, EXIT.INVALID_CONTRACT);
    }
    const content = fs.readFileSync(absolute, 'utf8').replaceAll('\r\n', '\n').trim();
    return { path: normalizePath(relativePath), content, hash: hashBytes(content) };
  });
}

function readBundledOverlay(profileId, type, id) {
  const overlayPath = path.join(projectRoot, 'profiles', 'overlays', profileId, type, `${id}.md`);
  if (!fs.existsSync(overlayPath)) return null;
  const content = fs.readFileSync(overlayPath, 'utf8').replaceAll('\r\n', '\n').trim();
  return { path: normalizePath(path.relative(projectRoot, overlayPath)), content, hash: hashBytes(content) };
}

function resolveInstallPackages(profile, policy) {
  const catalog = loadCatalog(projectRoot);
  const installProfile = structuredClone(profile);
  installProfile.packageAllowlist = {
    characters: [...policy.allowedCharacterPackages],
    skills: [...policy.allowedSkillPackages],
  };
  const resolution = resolveDependencies(catalog, installProfile);
  if (resolution.issues.length) {
    throw new HomerError('Install package dependency closure is invalid', EXIT.MISSING_DEPENDENCY,
      resolution.issues.map((item) => `${item.type}: ${item.package || item.path || item.dependency || item.message || ''}`));
  }
  enforceMinimumVersions(resolution.packages, policy);
  return { catalog, resolution };
}

function canonicalDescriptor(item) {
  const descriptor = structuredClone(item.descriptor);
  descriptor.provenance = {
    repository: 'https://github.com/StewieTech/Homer-Odyssey',
    commit: `package-${item.version}-${item.hash}`,
    paths: [item.descriptorPath],
  };
  descriptor.generatedBy = 'Homer Odyssey installer';
  descriptor.generatedSource = { path: item.descriptorPath, hash: item.hash };
  return descriptor;
}

function filteredDescriptor(item, policy) {
  const descriptor = canonicalDescriptor(item);
  const allowed = new Set(policy.capabilities.allowed);
  descriptor.capabilities = (descriptor.capabilities || []).filter((capability) => allowed.has(capability));
  if (descriptor.permissions?.requested) descriptor.permissions.requested = descriptor.permissions.requested.filter((capability) => allowed.has(capability));
  return descriptor;
}

function putDesired(desired, relativePath, content, source) {
  const normalized = normalizePath(relativePath);
  if (desired.has(normalized)) throw new HomerError(`Duplicate installer output: ${normalized}`, EXIT.INVALID_CONTRACT);
  desired.set(normalized, { content, hash: hashBytes(content), source });
}

function buildPackageOutputs(packages, profile, policy, targetOverlays) {
  const desired = new Map();
  const transformations = [];
  const findings = [];
  const processedCore = new Map();
  const overlayEvidence = [];
  const targetOverlayText = targetOverlays.map((item) => item.content).join('\n\n');

  for (const item of packages) {
    const plural = item.type === 'character' ? 'characters' : 'skills';
    const base = `.homer/generated/install/${plural}/${item.id}`;
    const descriptorName = item.type === 'character' ? 'passport.json' : 'manifest.json';
    const descriptor = filteredDescriptor(item, policy);
    const descriptorContent = `${stableJson(descriptor, 2)}\n`;
    findings.push(...scanSanitizedContent(descriptorContent, policy, `${base}/${descriptorName}`));
    putDesired(desired, `${base}/${descriptorName}`, descriptorContent, { package: item.key, sourcePath: item.descriptorPath });

    const bundledOverlay = readBundledOverlay(profile.id, plural, item.id);
    if (bundledOverlay) overlayEvidence.push({ package: item.key, scope: 'bundled', path: bundledOverlay.path, hash: bundledOverlay.hash });
    for (const surface of item.surfaces.filter((entry) => !entry.path.startsWith('adapter:'))) {
      let content = surface.content;
      if (surface.path === 'core.md') {
        if (bundledOverlay?.content) content = `${content.trim()}\n\n## Adapter overlay\n\n${bundledOverlay.content}\n`;
        if (targetOverlayText) content = `${content.trim()}\n\n## Target-owned policy overlay\n\n${targetOverlayText}\n`;
      }
      const sanitized = sanitizeText(content, policy, `${base}/${surface.path}`);
      transformations.push(...sanitized.transformations);
      findings.push(...scanSanitizedContent(sanitized.content, policy, `${base}/${surface.path}`));
      let rendered = sanitized.content;
      if (surface.path.endsWith('.md')) {
        rendered = `${GENERATED_MARKER}\n<!-- Canonical Homer package: ${item.key}@${item.version}; package-sha256: ${item.hash} -->\n\n${rendered.trim()}\n`;
      } else if (surface.path.endsWith('.json')) {
        try { rendered = `${stableJson(JSON.parse(rendered), 2)}\n`; }
        catch (error) { throw new HomerError(`Invalid packaged JSON ${item.key}:${surface.path}: ${error.message}`, EXIT.INVALID_CONTRACT); }
      }
      putDesired(desired, `${base}/${surface.path}`, rendered, { package: item.key, sourcePath: surface.sourcePath });
      if (surface.path === 'core.md') processedCore.set(item.key, sanitized.content.trim());
    }
  }
  for (const overlay of targetOverlays) overlayEvidence.push({ scope: 'target', path: overlay.path, hash: overlay.hash });
  return { desired, findings, overlayEvidence, processedCore, transformations };
}

function buildNativeSkills(state, packagesByKey, capabilityEvaluation, targetOverlayText) {
  const { desired, findings, policy, processedCore, profile, transformations } = state;
  for (const skillId of policy.allowedSkillPackages) {
    const skillPackage = packagesByKey.get(`skill:${skillId}`);
    const characterId = CHARACTER_BY_SKILL[skillId];
    const characterPackage = packagesByKey.get(`character:${characterId}`);
    if (!skillPackage || !characterPackage) {
      throw new HomerError(`Native skill binding is incomplete for ${skillId}: character:${characterId}`, EXIT.MISSING_DEPENDENCY);
    }
    const nativeName = policy.nativeSkillNames[skillId];
    const humanGated = capabilityEvaluation.humanGated
      .filter((item) => item.package === skillPackage.key || item.package === characterPackage.key)
      .map((item) => item.capability);
    const rendered = renderCodexTargetSkill({
      characterId,
      characterPackage,
      humanGatedCapabilities: [...new Set(humanGated)].sort(),
      nativeName,
      packageCore: processedCore.get(skillPackage.key) || '',
      profile,
      skillPackage,
      targetOverlay: targetOverlayText,
    });
    const relativePath = `.agents/skills/${nativeName}/SKILL.md`;
    findings.push(...scanSanitizedContent(rendered, policy, relativePath));
    putDesired(desired, relativePath, rendered, { package: skillPackage.key, character: characterPackage.key });
    transformations.push({ type: 'native-skill-render', surface: relativePath, package: skillPackage.key, character: characterPackage.key, afterHash: hashBytes(rendered) });
  }
}

function requiredDocs(targetRoot, policy) {
  const missing = policy.requiredSourceDocs.filter((relativePath) => !fs.existsSync(targetPath(targetRoot, relativePath)));
  if (missing.length) throw new HomerError('Target-required source documents are missing', EXIT.INVALID_CONTRACT, missing);
}

function readInstallLock(targetRoot) {
  const lockPath = targetPath(targetRoot, INSTALL_LOCK_PATH);
  if (!fs.existsSync(lockPath)) return { content: '', lock: null };
  const content = fs.readFileSync(lockPath, 'utf8');
  const lock = assertContract('install-lock', readJson(lockPath, 'Homer install lock'));
  return { content, lock };
}

function analyzeOwnership(targetRoot, policy, desired, previousLock) {
  const previousEntries = new Map((previousLock?.generatedFiles || []).map((item) => [normalizePath(item.path), item]));
  const conflicts = [];
  const desiredPaths = new Set(desired.keys());
  const removals = [];

  for (const managedRoot of policy.managedNativeSkillPaths) {
    const absoluteRoot = targetPath(targetRoot, managedRoot);
    if (!fs.existsSync(absoluteRoot)) continue;
    const priorUnderRoot = [...previousEntries.keys()].filter((item) => item.startsWith(`${normalizePath(managedRoot)}/`));
    const existing = walkFiles(absoluteRoot).map((item) => normalizePath(`${managedRoot}/${item}`));
    if (!priorUnderRoot.length && !existing.length) conflicts.push({ type: 'unmanaged-native-skill', path: normalizePath(managedRoot), localHash: hashObject([]), proposedHash: hashObject([...desiredPaths].filter((item) => item.startsWith(`${normalizePath(managedRoot)}/`))) });
    for (const relativePath of existing) {
      const prior = previousEntries.get(relativePath);
      const content = fs.readFileSync(targetPath(targetRoot, relativePath));
      const actualHash = hashBytes(content);
      if (!prior) conflicts.push({ type: 'unmanaged-native-skill', path: relativePath, localHash: actualHash, proposedHash: desired.get(relativePath)?.hash || '' });
      else if (prior.hash !== actualHash || (relativePath.endsWith('/SKILL.md') && !content.toString('utf8').includes(TARGET_MARKER))) {
        conflicts.push({ type: 'managed-native-skill-drift', path: relativePath, localHash: actualHash, expectedHash: prior.hash, proposedHash: desired.get(relativePath)?.hash || '' });
      }
    }
  }

  for (const [relativePath, output] of desired) {
    assertInstallerPath(relativePath, policy);
    const absolute = targetPath(targetRoot, relativePath);
    if (!fs.existsSync(absolute)) continue;
    const actual = fs.readFileSync(absolute);
    const actualHash = hashBytes(actual);
    const prior = previousEntries.get(relativePath);
    if (!prior || prior.hash !== actualHash) conflicts.push({ type: 'unmanaged-install-path', path: relativePath, localHash: actualHash, proposedHash: output.hash, expectedHash: prior?.hash || '' });
  }

  for (const [relativePath, prior] of previousEntries) {
    if (desiredPaths.has(relativePath)) continue;
    assertInstallerPath(relativePath, policy);
    const absolute = targetPath(targetRoot, relativePath);
    const actualHash = fs.existsSync(absolute) ? hashBytes(fs.readFileSync(absolute)) : '';
    if (actualHash !== prior.hash) conflicts.push({ type: 'managed-removal-drift', path: relativePath, localHash: actualHash, expectedHash: prior.hash, proposedHash: '' });
    else removals.push(relativePath);
  }
  return {
    conflicts: [...new Map(conflicts.map((item) => [`${item.type}:${item.path}`, item])).values()].sort((left, right) => `${left.path}:${left.type}`.localeCompare(`${right.path}:${right.type}`)),
    removals: removals.sort(),
  };
}

function buildSanitizationReport({ capabilityEvaluation, findings, overlayEvidence, packages, policy, profileHash, transformations }) {
  return assertContract('sanitization-report', {
    apiVersion: API_VERSION,
    kind: 'SanitizationReport',
    policy: { version: policy.version, profileHash, targetRepository: policy.targetRepository, targetBaseBranch: policy.targetBaseBranch },
    canonicalSource: { repository: 'https://github.com/StewieTech/Homer-Odyssey', version: VERSION },
    packages: packages.map((item) => ({ id: item.key, version: item.version, hash: item.hash })).sort((left, right) => left.id.localeCompare(right.id)),
    overlays: overlayEvidence.sort((left, right) => `${left.scope}:${left.path}`.localeCompare(`${right.scope}:${right.path}`)),
    transformations: transformations.sort((left, right) => stableJson(left).localeCompare(stableJson(right))),
    generalized: transformations.filter((item) => item.type !== 'native-skill-render'),
    replaced: transformations.filter((item) => item.type.includes('substitution')),
    removed: capabilityEvaluation.humanGated.map((item) => ({ ...item, reason: 'human-gated-authority-not-granted' })),
    humanGated: capabilityEvaluation.humanGated,
    denied: [...capabilityEvaluation.denied, ...findings],
    validationCommands: policy.validationCommands,
    localPrecedence: policy.localPrecedence,
  });
}

function buildInstallPlan({ targetRoot, profile: profileValue }) {
  const resolvedTarget = path.resolve(targetRoot || '.');
  if (!fs.existsSync(resolvedTarget) || !fs.statSync(resolvedTarget).isDirectory()) throw new HomerError(`Target root does not exist: ${resolvedTarget}`, EXIT.INVALID_CONTRACT);
  const loaded = resolveTargetProfile(resolvedTarget, profileValue);
  const { policy, profile, profileHash } = loaded;
  requiredDocs(resolvedTarget, policy);
  const targetOverlays = readTargetOverlays(resolvedTarget, policy);
  const { catalog, resolution } = resolveInstallPackages(profile, policy);
  const capabilityEvaluation = evaluatePackageCapabilities(resolution.packages, policy);
  const packageOutputs = buildPackageOutputs(resolution.packages, profile, policy, targetOverlays);
  const packagesByKey = new Map(resolution.packages.map((item) => [item.key, item]));
  const state = { ...packageOutputs, policy, profile };
  buildNativeSkills(state, packagesByKey, capabilityEvaluation, targetOverlays.map((item) => item.content).join('\n\n'));
  const report = buildSanitizationReport({
    capabilityEvaluation,
    findings: state.findings,
    overlayEvidence: state.overlayEvidence,
    packages: resolution.packages,
    policy,
    profileHash,
    transformations: state.transformations,
  });
  if (capabilityEvaluation.denied.length) {
    throw new HomerError('Denied or undeclared capability in install dependency closure', EXIT.UNSAFE_PRIVILEGE,
      [stableJson(report)]);
  }
  if (state.findings.length) {
    throw new HomerError('Sanitization rejected generated install content', EXIT.SECURITY_POLICY,
      [stableJson(report)]);
  }
  const reportContent = `${stableJson(report, 2)}\n`;
  putDesired(state.desired, policy.evidenceOutputPath, reportContent, { type: 'sanitization-report' });
  const previous = readInstallLock(resolvedTarget);
  const ownership = analyzeOwnership(resolvedTarget, policy, state.desired, previous.lock);
  const writes = [...state.desired.entries()]
    .filter(([relativePath, output]) => {
      const absolute = targetPath(resolvedTarget, relativePath);
      return !fs.existsSync(absolute) || hashBytes(fs.readFileSync(absolute)) !== output.hash;
    })
    .map(([relativePath]) => relativePath)
    .sort();
  return {
    apiVersion: API_VERSION,
    kind: 'HomerInstallPlan',
    targetRoot: resolvedTarget,
    profilePath: loaded.profilePath,
    profile,
    policy,
    profileHash,
    sourceHash: hashObject(catalog.packages.map((item) => ({ id: item.key, version: item.version, hash: item.hash }))),
    targetInputHash: targetOwnedFingerprint(resolvedTarget, policy),
    packages: resolution.packages,
    desired: state.desired,
    report,
    capabilityEvaluation,
    conflicts: ownership.conflicts,
    writes,
    removals: ownership.removals,
    previous,
  };
}

function makeInstallLock(plan, backups) {
  return assertContract('install-lock', {
    apiVersion: API_VERSION,
    kind: 'HomerInstallLock',
    generatedBy: 'Homer Odyssey installer',
    installerVersion: VERSION,
    profile: { path: normalizePath(path.relative(plan.targetRoot, plan.profilePath)), hash: plan.profileHash, sanitizationVersion: plan.policy.version },
    target: { repository: plan.policy.targetRepository, baseBranch: plan.policy.targetBaseBranch, inputHash: plan.targetInputHash },
    canonicalSource: { repository: 'https://github.com/StewieTech/Homer-Odyssey', hash: plan.sourceHash },
    packages: plan.packages.map((item) => ({ id: item.key, version: item.version, hash: item.hash })).sort((left, right) => left.id.localeCompare(right.id)),
    generatedFiles: [...plan.desired.entries()].map(([relativePath, output]) => ({ path: relativePath, hash: output.hash, source: output.source })).sort((left, right) => left.path.localeCompare(right.path)),
    sanitizationReport: { path: plan.policy.evidenceOutputPath, hash: plan.desired.get(plan.policy.evidenceOutputPath).hash },
    rollback: {
      previousLockHash: plan.previous.content ? hashBytes(plan.previous.content) : '',
      previousLockBase64: plan.previous.content ? Buffer.from(plan.previous.content).toString('base64') : '',
      files: backups.sort((left, right) => left.path.localeCompare(right.path)),
    },
  });
}

function installTarget(options) {
  const plan = buildInstallPlan(options);
  if (plan.conflicts.length) {
    const conflictReport = {
      apiVersion: API_VERSION,
      kind: 'SemanticInstallConflictReport',
      status: 'rejected',
      policy: {
        profileHash: plan.profileHash,
        failOnUnmanagedConflict: plan.policy.failOnUnmanagedConflict,
      },
      target: {
        repository: plan.policy.targetRepository,
        baseBranch: plan.policy.targetBaseBranch,
      },
      conflicts: plan.conflicts.map((item) => ({
        ...item,
        comparison: {
          contentMatches: Boolean(item.localHash && item.proposedHash && item.localHash === item.proposedHash),
          localHash: item.localHash || '',
          proposedHash: item.proposedHash || '',
          expectedManagedHash: item.expectedHash || '',
        },
      })),
    };
    throw new HomerError('Installer found unmanaged or drifted content and will not overwrite it', EXIT.CUSTOMIZATION_CONFLICT,
      [stableJson(conflictReport)]);
  }
  const existingLockMatches = plan.previous.lock
    && plan.previous.lock.profile.hash === plan.profileHash
    && plan.previous.lock.canonicalSource.hash === plan.sourceHash
    && plan.previous.lock.target.inputHash === plan.targetInputHash
    && hashObject(plan.previous.lock.generatedFiles) === hashObject([...plan.desired.entries()].map(([relativePath, output]) => ({ path: relativePath, hash: output.hash, source: output.source })).sort((left, right) => left.path.localeCompare(right.path)));
  if (!plan.writes.length && !plan.removals.length && existingLockMatches) {
    return { apiVersion: API_VERSION, kind: 'HomerInstall', dryRun: Boolean(options.dryRun), idempotent: true, writes: [], removals: [], lockPath: INSTALL_LOCK_PATH, reportPath: plan.policy.evidenceOutputPath };
  }
  const changedPaths = [...new Set([...plan.writes, ...plan.removals])].sort();
  const backups = changedPaths.map((relativePath) => {
    const absolute = targetPath(plan.targetRoot, relativePath);
    const existed = fs.existsSync(absolute);
    return { path: relativePath, existed, contentBase64: existed ? fs.readFileSync(absolute).toString('base64') : '' };
  });
  const lock = makeInstallLock(plan, backups);
  if (options.dryRun) {
    return { apiVersion: API_VERSION, kind: 'HomerInstall', dryRun: true, idempotent: false, writes: plan.writes, removals: plan.removals, lockPath: INSTALL_LOCK_PATH, reportPath: plan.policy.evidenceOutputPath, lockHash: hashObject(lock), report: plan.report };
  }
  const lockPath = targetPath(plan.targetRoot, INSTALL_LOCK_PATH);
  try {
    for (const relativePath of plan.writes) atomicWrite(targetPath(plan.targetRoot, relativePath), plan.desired.get(relativePath).content);
    for (const relativePath of plan.removals) {
      const absolute = targetPath(plan.targetRoot, relativePath);
      if (fs.existsSync(absolute)) fs.rmSync(absolute);
    }
    atomicWrite(lockPath, `${stableJson(lock, 2)}\n`);
  } catch (error) {
    for (const backup of backups) {
      const absolute = targetPath(plan.targetRoot, backup.path);
      if (backup.existed) atomicWrite(absolute, Buffer.from(backup.contentBase64, 'base64'));
      else if (fs.existsSync(absolute)) fs.rmSync(absolute);
    }
    if (plan.previous.content) atomicWrite(lockPath, plan.previous.content);
    else if (fs.existsSync(lockPath)) fs.rmSync(lockPath);
    throw error;
  }
  return { apiVersion: API_VERSION, kind: 'HomerInstall', dryRun: false, idempotent: false, writes: plan.writes, removals: plan.removals, lockPath: INSTALL_LOCK_PATH, reportPath: plan.policy.evidenceOutputPath, lockHash: hashObject(lock) };
}

function verifyInstall(options) {
  const plan = buildInstallPlan(options);
  const drift = [...plan.writes.map((relativePath) => ({ type: 'content-drift', path: relativePath })), ...plan.removals.map((relativePath) => ({ type: 'unexpected-owned-file', path: relativePath })), ...plan.conflicts];
  const lock = plan.previous.lock;
  if (!lock) drift.push({ type: 'missing-install-lock', path: INSTALL_LOCK_PATH });
  else {
    if (lock.profile.hash !== plan.profileHash) drift.push({ type: 'profile-drift', path: normalizePath(path.relative(plan.targetRoot, plan.profilePath)) });
    if (lock.canonicalSource.hash !== plan.sourceHash) drift.push({ type: 'canonical-package-drift', path: 'packages/**' });
    if (lock.target.inputHash !== plan.targetInputHash) drift.push({ type: 'target-input-drift', path: 'target-owned/**' });
  }
  return {
    apiVersion: API_VERSION,
    kind: 'HomerInstallVerification',
    verdict: drift.length ? 'FAILED' : 'PASS',
    exitCode: drift.length ? EXIT.DRIFT : EXIT.OK,
    drift: drift.sort((left, right) => `${left.path}:${left.type}`.localeCompare(`${right.path}:${right.type}`)),
    reportPath: plan.policy.evidenceOutputPath,
  };
}

function rollbackInstall(options) {
  const targetRoot = path.resolve(options.targetRoot || '.');
  const loaded = resolveTargetProfile(targetRoot, options.profile);
  const current = readInstallLock(targetRoot);
  if (!current.lock) throw new HomerError('No Homer install lock exists', EXIT.ROLLBACK_FAILED);
  const actions = [];
  for (const generated of current.lock.generatedFiles) {
    assertInstallerPath(generated.path, loaded.policy);
    const absolute = targetPath(targetRoot, generated.path);
    const actualHash = fs.existsSync(absolute) ? hashBytes(fs.readFileSync(absolute)) : '';
    if (actualHash !== generated.hash) throw new HomerError(`Rollback refuses drifted installer output: ${generated.path}`, EXIT.ROLLBACK_FAILED);
  }
  for (const backup of current.lock.rollback.files) actions.push({ type: backup.existed ? 'restore' : 'remove', path: backup.path });
  actions.sort((left, right) => left.path.localeCompare(right.path));
  if (options.dryRun) return { apiVersion: API_VERSION, kind: 'HomerInstallRollback', dryRun: true, actions };
  const backupByPath = new Map(current.lock.rollback.files.map((item) => [item.path, item]));
  for (const action of actions) {
    const backup = backupByPath.get(action.path);
    const absolute = targetPath(targetRoot, action.path);
    if (backup.existed) atomicWrite(absolute, Buffer.from(backup.contentBase64, 'base64'));
    else if (fs.existsSync(absolute)) fs.rmSync(absolute);
    const nativeRoot = loaded.policy.managedNativeSkillPaths.find((root) => normalizePath(action.path).startsWith(`${normalizePath(root)}/`));
    if (nativeRoot) removeEmptyParents(targetRoot, action.path, nativeRoot);
  }
  const lockPath = targetPath(targetRoot, INSTALL_LOCK_PATH);
  if (current.lock.rollback.previousLockBase64) {
    const previous = Buffer.from(current.lock.rollback.previousLockBase64, 'base64');
    if (hashBytes(previous) !== current.lock.rollback.previousLockHash) throw new HomerError('Previous install lock backup is corrupt', EXIT.ROLLBACK_FAILED);
    atomicWrite(lockPath, previous);
  } else if (fs.existsSync(lockPath)) fs.rmSync(lockPath);
  return { apiVersion: API_VERSION, kind: 'HomerInstallRollback', dryRun: false, actions };
}

function safeDenyProfile() {
  return {
    apiVersion: API_VERSION,
    kind: 'TargetProfile',
    id: 'review-required',
    version: '1.0.0',
    displayName: 'Review required before Homer installation',
    lockfile: 'homer.lock',
    capabilities: { allowed: ['filesystem.read'], humanGated: [], denied: ['external.publish', 'filesystem.write', 'github.write', 'production.deploy', 'production.mutate', 'pull-request.merge', 'secret.export'] },
    paths: { protected: ['.agents/**', '.github/**', 'AGENTS.md', 'agent.md', 'CONTEXT.md', 'docs/**', 'src/**'], managed: ['.homer/generated/install/**'] },
    sources: [{ id: 'homer-odyssey', url: 'https://github.com/StewieTech/Homer-Odyssey', role: 'canonical' }],
    vocabulary: { agent: 'character', operation: 'review', plan: 'reviewed plan', product: 'target' },
    validationCommands: [],
    overlays: [],
    packageAllowlist: { characters: [], skills: [] },
    projection: { generatedMarker: GENERATED_MARKER, mappings: [{ source: 'packages/**', target: '.homer/generated/install/**' }] },
    sanitization: {
      version: '1.0.0',
      targetRepository: 'POLICY_REVIEW_REQUIRED',
      targetBaseBranch: 'POLICY_REVIEW_REQUIRED',
      allowedCharacterPackages: [],
      allowedSkillPackages: [],
      nativeSkillNames: {},
      targetVocabulary: { agent: 'character', operation: 'review', plan: 'reviewed plan', product: 'target' },
      requiredSourceDocs: ['AGENTS.md'],
      validationCommands: [],
      substitutions: { paths: {}, repositories: {}, branches: {} },
      capabilities: { allowed: ['filesystem.read'], humanGated: [], denied: ['external.publish', 'filesystem.write', 'github.write', 'production.deploy', 'production.mutate', 'pull-request.merge', 'secret.export'] },
      deniedPatterns: ['StewieTech/Pariss', 'developSIT', '\\bsk-[A-Za-z0-9_-]{12,}\\b', '\\bghp_[A-Za-z0-9]{20,}\\b', '\\bAKIA[A-Z0-9]{16}\\b'],
      protectedPaths: ['.agents/**', '.github/**', 'AGENTS.md', 'agent.md', 'CONTEXT.md', 'docs/**', 'src/**'],
      managedNativeSkillPaths: [],
      localPrecedence: ['AGENTS.md', 'agent.md', 'CONTEXT.md', 'docs/adr/**'],
      requiredOverlays: [],
      minimumPackageVersions: {},
      failOnUnresolvedPlaceholder: true,
      failOnSourceSpecificLeakage: true,
      failOnUnmanagedConflict: true,
      evidenceOutputPath: '.homer/generated/install/sanitization-report.json',
    },
  };
}

function initializeTarget({ targetRoot, profile: profileValue }) {
  const resolvedTarget = path.resolve(targetRoot || '.');
  if (!fs.existsSync(resolvedTarget) || !fs.statSync(resolvedTarget).isDirectory()) throw new HomerError(`Target root does not exist: ${resolvedTarget}`, EXIT.INVALID_CONTRACT);
  if (!profileValue) throw new HomerError('homer install --init-target requires --profile <target-profile-path>', EXIT.USAGE);
  const profilePath = path.isAbsolute(profileValue) ? path.resolve(profileValue) : path.resolve(resolvedTarget, profileValue);
  if (!isInside(resolvedTarget, profilePath)) throw new HomerError('Install profile must be owned by the target repository', EXIT.INVALID_CONTRACT);
  const adrPath = path.join(resolvedTarget, '.homer', 'adr', '0001-homer-target-sanitization.md');
  const existing = [profilePath, adrPath].filter((item) => fs.existsSync(item));
  if (existing.length) throw new HomerError('Target initialization refuses to overwrite existing policy or ADR', EXIT.CUSTOMIZATION_CONFLICT, existing);
  const profileContent = `${stableJson(safeDenyProfile(), 2)}\n`;
  const adrContent = `# ADR 0001: Homer target sanitization policy\n\nStatus: Policy review required\n\n## Context\n\nHomer can project canonical character packages into native Codex skills. The target profile is executable policy; this ADR records the target-owned rationale.\n\n## Decision required\n\nReview repository identity, base branch, package allowlists, exact native skill paths, capabilities, substitutions, overlays, protected paths, validation commands, and minimum versions. Keep generated output read-only and preserve local rules as higher precedence.\n\n## Consequences\n\nNo installation is permitted until the safe-deny profile is reviewed and updated.\n`;
  atomicWrite(profilePath, profileContent);
  atomicWrite(adrPath, adrContent);
  const relativeProfile = normalizePath(path.relative(resolvedTarget, profilePath));
  return {
    apiVersion: API_VERSION,
    kind: 'HomerTargetInitialization',
    status: 'policy-review-required',
    exitCode: EXIT.POLICY_REVIEW_REQUIRED,
    writes: [normalizePath(path.relative(resolvedTarget, adrPath)), relativeProfile].sort(),
    installedSkills: [],
    followUp: `npx --yes @stewietech/homer-odyssey install --target . --profile ${relativeProfile}`,
  };
}

module.exports = {
  CHARACTER_BY_SKILL,
  GENERATED_MARKER,
  INSTALL_LOCK_PATH,
  buildInstallPlan,
  initializeTarget,
  installTarget,
  rollbackInstall,
  verifyInstall,
};
